package com.fenghuang.caipiaobao.constant

/**
 * 页面跳转的Intent常量
 */
object IntentConstant {

    const val PASSWORD = "123456"

    const val HOME_LIVE_CHAT_ANCHOR_ID = "HOME_LIVE_CHAT_ANCHOR_ID"
    const val HOME_LIVE_CHAT_TITLE = "HOME_LIVE_CHAT_TITLE"
    const val HOME_LIVE_ANCHOR_DATA = "HOME_LIVE_ANCHOR_DATA"


    const val LOTTERY_HISTORY_OPEN_CODE_ID = "LOTTERY_HISTORY_OPEN_CODE_ID"
    const val LOTTERY_EXPERT_LOTTERY_ID = "LOTTERY_EXPERT_LOTTERY_ID"
    const val LOTTERY_EXPERT_LOTTERY_ISSUE = "LOTTERY_EXPERT_LOTTERY_ISSUE"

    const val MINE_USER_BALANCE = "MINE_USER_BALANCE"

    const val MINE_CHANNELS_ID = "MINE_INVEST_ID"

    const val MINE_USER_ID = "MINE_USER_ID"

    const val MINE_INVEST_AMOUNT = "MINE_INVEST_AMOUNT"
}